import {
  ServerCog,
  ToggleLeft,
  CircleDot,
  Gamepad2,
  Radar,
  Waves,
  Thermometer,
  Flame,
  AppWindow,
  DoorOpen,
  Nfc,
  Lock,
  PhoneCall,
  Lightbulb,
  LampCeiling,
  Minus,
  SlidersHorizontal,
  Blinds,
  Gauge,
  AirVent,
  Fan,
  Siren,
  Server,
  Speaker,
  Plug2,
  Router,
  Cable,
  BatteryCharging,
  Battery,
  Zap,
  CircuitBoard,
  type LucideIcon,
} from "lucide-react";
import type { SmartHomeIconKey } from "@/domain";

/** Shared icon set for the Loxone device catalog (Phase 13) — a small set
 * of lucide-react icons covers ~110 products; the category/technology
 * `color` on each catalog entry does the real at-a-glance differentiation
 * (§28), not a bespoke pictogram per SKU. Keep this the single place
 * mapping `SmartHomeIconKey` → component so the canvas and the Inspector
 * never drift apart. */
export const SMART_HOME_ICONS: Record<SmartHomeIconKey, LucideIcon> = {
  controller: ServerCog,
  touch: ToggleLeft,
  button: CircleDot,
  remote: Gamepad2,
  presence: Radar,
  motion: Waves,
  "climate-sensor": Thermometer,
  smoke: Flame,
  "window-contact": AppWindow,
  "door-contact": DoorOpen,
  nfc: Nfc,
  "door-lock": Lock,
  intercom: PhoneCall,
  spot: Lightbulb,
  "ceiling-light": LampCeiling,
  "led-strip": Minus,
  dimmer: SlidersHorizontal,
  shading: Blinds,
  valve: Gauge,
  ac: AirVent,
  ventilation: Fan,
  siren: Siren,
  "audio-server": Server,
  speaker: Speaker,
  outlet: Plug2,
  network: Router,
  extension: Cable,
  "energy-meter": BatteryCharging,
  "power-supply": Battery,
  relay: Zap,
  "io-module": CircuitBoard,
};
