import type { Point } from "./geometry";
import type { ElectricalDeviceType } from "./electrical";
import type { CableType } from "./routing";

/**
 * Smart-home integrations (Loxone and future systems) must stay generic —
 * never hard-coded as `if (loxone)` throughout the app (§56). Loxone is
 * just the first entry in SMART_HOME_CATALOGS; a second system adds its
 * own catalog entry, no branching logic elsewhere.
 */
export interface SmartHomeSystem {
  id: string;
  name: string;
}

/** A standalone smart-home device placed directly on the plan — not tied
 * to one of the five electrical device categories (e.g. a Weather Station
 * mounted outside, or a Room Comfort Sensor floating in a room with no
 * outlet/light of its own). Point-mounted like a ceiling device (§66);
 * the user picks any catalog model freely, not narrowed by category. */
export interface SmartHomeDevice {
  id: string;
  floorId: string;
  systemId: string;
  modelId: string;
  position: Point;
  roomId: string | null;
  /** Which Tree branch this device's Tree bus cable belongs to — only
   * meaningful when the model is a Tree device. */
  treeBranchId?: string;
  /** Which Audio zone this speaker belongs to (§12) — only meaningful for
   * technology "audio" models. */
  audioZoneId?: string;
  /** Auto-assigned display number (§26), unique per prefix per floor. */
  number: number;
}

export const LOXONE_SYSTEM: SmartHomeSystem = {
  id: "loxone",
  name: "Loxone",
};

/** Broad hardware role, used to suggest relevant catalog entries for a
 * given electrical device type rather than showing the entire catalog
 * everywhere. */
export type SmartHomeDeviceCategory =
  | "controller"
  | "actuator"
  | "input"
  | "sensor"
  | "climate";

export const SMART_HOME_CATEGORY_LABELS: Record<SmartHomeDeviceCategory, string> = {
  controller: "Steuerung",
  actuator: "Aktor",
  input: "Bedienung",
  sensor: "Sensor",
  climate: "Klima",
};

/**
 * The floorplan-section taxonomy from the Loxone device library spec —
 * distinct from `category` above (the internal hardware-role field used
 * for numbering prefixes and device-type-narrowed pickers). This is
 * purely the user-facing grouping: which toolbar section / sidebar
 * bucket a catalog entry belongs to.
 *
 * 11 values, not the spec's literal top-level 10 — "netzwerk" is added
 * because the spec's own §29 toolbar layout calls out a dedicated
 * "🌐 Netzwerk" group (LAN/WLAN AP/TV-SAT) that the 10-item list omits.
 */
export type PlanningCategory =
  | "geraete-raum"
  | "beleuchtung"
  | "beschattung"
  | "heizung-klima"
  | "sicherheit-zutritt"
  | "audio"
  | "steckdosen-strom"
  | "netzwerk"
  | "aussenbereich"
  | "schaltschrank-technik"
  | "schnittstellen-extensions";

export const PLANNING_CATEGORY_LABELS: Record<PlanningCategory, string> = {
  "geraete-raum": "Geräte im Raum",
  beleuchtung: "Beleuchtung",
  beschattung: "Beschattung",
  "heizung-klima": "Heizung / Klima",
  "sicherheit-zutritt": "Sicherheit / Zutritt",
  audio: "Audio",
  "steckdosen-strom": "Steckdosen / Stromanschlüsse",
  netzwerk: "Netzwerk",
  aussenbereich: "Außenbereich",
  "schaltschrank-technik": "Schaltschrank / Technik",
  "schnittstellen-extensions": "Schnittstellen / Extensions",
};

/** Display order for the picker's `<optgroup>`s — the spec's own section
 * order, with "Netzwerk" folded in next to "Steckdosen / Stromanschlüsse"
 * since both are building-infrastructure connections. */
export const PLANNING_CATEGORY_ORDER: PlanningCategory[] = [
  "geraete-raum",
  "beleuchtung",
  "beschattung",
  "heizung-klima",
  "sicherheit-zutritt",
  "audio",
  "steckdosen-strom",
  "netzwerk",
  "aussenbereich",
  "schaltschrank-technik",
  "schnittstellen-extensions",
];

/** How a device physically connects — the layer a planner actually cares
 * about when tracing cable runs, distinct from `technology` below (which
 * groups Tree/Air/audio/network/230V purely for cabling-computation
 * purposes). */
export type ConnectionType =
  | "Tree"
  | "Air"
  | "WiFi"
  | "230V"
  | "24V DC"
  | "potentialfrei"
  | "KNX"
  | "DALI"
  | "DMX"
  | "Modbus"
  | "RS232"
  | "RS485"
  | "EnOcean"
  | "1-Wire"
  | "M-Bus"
  | "IR"
  | "Ethernet";

export type MountingType =
  | "Wand"
  | "Decke"
  | "Fenster/Tür"
  | "Außenwand"
  | "Schaltschrank/Hutschiene"
  | "Technikraum"
  | "frei"
  | "Boden";

export type PowerSupply = "24V DC" | "230V AC" | "Tree-Bus" | "Batterie" | "PoE" | "keine";

/** String key into the shared lucide-react icon lookup
 * (`src/features/editor/smart-home-icons.ts`) — deliberately not a
 * bespoke SVG per catalog entry; a shared icon set covers ~110 products
 * with the category/technology color doing the real at-a-glance work
 * (§28), while closely related products (e.g. every AC-brand variant)
 * legitimately share one icon. */
export type SmartHomeIconKey =
  | "controller"
  | "touch"
  | "button"
  | "remote"
  | "presence"
  | "motion"
  | "climate-sensor"
  | "smoke"
  | "window-contact"
  | "door-contact"
  | "nfc"
  | "door-lock"
  | "intercom"
  | "spot"
  | "ceiling-light"
  | "led-strip"
  | "dimmer"
  | "shading"
  | "valve"
  | "ac"
  | "ventilation"
  | "siren"
  | "audio-server"
  | "speaker"
  | "outlet"
  | "network"
  | "extension"
  | "energy-meter"
  | "power-supply"
  | "relay"
  | "io-module";

/** Which physical layer a device belongs to — the load-bearing distinction
 * for cabling (§33/§60): Tree devices share one bus per branch, Air
 * devices are wireless (no Tree cable at all), audio/network/230V each
 * get their own separate cable type and are never counted as Tree. */
export type SmartHomeTechnology = "loxone-tree" | "loxone-air" | "network" | "audio" | "230v";

export interface SmartHomeDeviceModel {
  id: string;
  systemId: string;
  category: SmartHomeDeviceCategory;
  planningCategory: PlanningCategory;
  label: string;
  description: string;
  technology: SmartHomeTechnology;
  connectionType: ConnectionType;
  icon: SmartHomeIconKey;
  /** Hex color — how this device renders on the plan and in lists, per
   * the §28 palette (Tree=green, Air=blue, Beleuchtung=gelb, ...). */
  color: string;
  mountingType: MountingType;
  /** Reference/BOM field, not read by the cable-length routing engine
   * (see Phase 13 plan §"key scoping decisions" #3) — omitted for
   * wireless (Air/WiFi) devices that genuinely have no cable of their
   * own to plan. */
  cableType?: CableType;
  powerSupply: PowerSupply;
  /** True only for genuine Loxone Tree devices — these share a Tree bus
   * and count against a branch's 50-device / 500m limits. Air, network,
   * audio and 230V hardware are never Tree devices even though some sit
   * in the same physical room (§62). */
  countsAsTreeDevice: boolean;
  /** Whether this device gets a symbol placed directly on the 2D
   * floorplan (a room device) vs. only ever appears in the Schaltschrank
   * parts list (§9/§22 — Extensions, power supplies, energy meters, the
   * Miniserver itself never sit "in a room" on the plan). */
  isPlanableOnFloorplan: boolean;
  /** Whether this device belongs in the Schaltschrank (cabinet) parts
   * list — independent of isPlanableOnFloorplan; almost always the
   * opposite of it, but kept as its own field rather than derived, since
   * a future device could conceivably be neither (e.g. a pure software
   * integration). */
  isCabinetComponent: boolean;
  /** §5 — a superseded/discontinued product, hidden from the picker by
   * default (still plannable for an existing installation being
   * extended, via "Legacy-Geräte anzeigen"). Absent/false = current. */
  legacy?: boolean;
}

const TREE = "#7A9D6E";
const AIR = "#4A8FA8";
const LIGHT = "#D9A441";
const RGBW = "#8F6FB8";
const CONTACT = "#8FB8D9";
const OUTLET = "#B23A3A";
const NETWORK = "#C9822E";
const AUDIO = "#B8698A";
const SHADING = "#8B5E3C";
const HEATING = "#B8542E";
const SECURITY = "#8C2F2F";
const ACCESS = "#6B4E8F";
const CABINET = "#6B6459";

/**
 * Loxone's Tree/Air product line, mapped from the user-supplied device
 * library reference — the genuine hardware names a planner would assign,
 * not a fabricated placeholder catalog.
 *
 * NOT live-verified: this session has no network access to loxone.com
 * (blocked by egress policy), so exact current product names/availability
 * come from the supplied reference plus training knowledge, not a live
 * fetch of Loxone's current lineup. Treat this as a strong starting point
 * to review against official Loxone documentation before ordering
 * hardware, not as a verified source of truth (§46).
 *
 * Deliberately NOT included (see Phase 13 plan): §26's third-party
 * integrations (Aquastar, Belimo, Gardena, Husqvarna, Tesla Powerwall,
 * Fronius, Miele@home, BMW CarData, EEBUS, OCPP, MQTT, Hunter Douglas,
 * Hörmann) — these need their own connector/config UI, not just a
 * catalog row, exactly as the spec's own §26 note anticipates.
 */
export const LOXONE_CATALOG: SmartHomeDeviceModel[] = [
  // 1. Zentrale Komponenten
  {
    id: "loxone-miniserver-gen2",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Miniserver Gen. 2",
    description: "Zentrale Steuereinheit der gesamten Loxone-Installation.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "controller",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-miniserver-gen1",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Miniserver (Gen. 1)",
    description:
      "Vorgängergeneration des Miniservers, durch Gen. 2 abgelöst — nur für die Erweiterung bestehender Altinstallationen relevant.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "controller",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
    legacy: true,
  },
  {
    id: "loxone-miniserver-compact",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Miniserver Compact",
    description: "Kompakte Miniserver-Variante für kleinere Installationen.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "controller",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-miniserver-go",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Miniserver Go",
    description: "Kompakter Miniserver mit Loxone Air, frei oder im Technikraum montierbar.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "controller",
    color: CABINET,
    mountingType: "frei",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },

  // 2. Taster und Bedienelemente
  {
    id: "loxone-touch-pure-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Pure Tree",
    description: "Moderner Loxone-Raumtaster mit Temperaturfühler und Statusanzeige.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "touch",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-pure-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Pure Air",
    description: "Touch Pure per Loxone Air statt Tree.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "touch",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-pure-display-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Pure Display Tree",
    description: "Touch-Bedienelement mit Display.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "touch",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-pure-display-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Pure Display Air",
    description: "Touch Pure Display per Loxone Air.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "touch",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-pure-display-co2-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Pure Display CO2 Tree",
    description: "Touch Pure Display mit zusätzlicher CO₂-Messung.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "touch",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-pure-display-co2-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Pure Display CO2 Air",
    description: "Air-Variante des Touch Pure Display mit CO₂-Messung.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "touch",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Tree",
    description: "Einfacher beleuchteter Wandtaster.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "touch",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Air",
    description: "Air-Ausführung des Standard-Loxone-Tasters.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "touch",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-pure-flex",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Pure Flex",
    description: "Rahmenloser Wandtaster für den flächenbündigen Einbau.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "touch",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-nightlight-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Touch Nightlight Air",
    description: "Taster mit integriertem Nachtlicht / Orientierungslicht.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "touch",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-touch-grill-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "aussenbereich",
    label: "Touch & Grill Air",
    description: "Bedienelement für Grill-/Außenanwendungen.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "touch",
    color: AIR,
    mountingType: "Außenwand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-button-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Button Air",
    description: "Einfacher Funk-Taster.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "button",
    color: AIR,
    mountingType: "frei",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-wrist-button-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Wrist Button Air",
    description: "Mobiler Funk-Taster zum Tragen am Handgelenk.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "button",
    color: AIR,
    mountingType: "frei",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: false,
  },
  {
    id: "loxone-remote-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Remote Air",
    description: "Fernbedienung für mehrere Funktionen.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "remote",
    color: AIR,
    mountingType: "frei",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: false,
  },
  {
    id: "loxone-remote-mini-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Remote Mini Air",
    description: "Kleine Fernbedienung.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "remote",
    color: AIR,
    mountingType: "frei",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: false,
  },

  // 3. Bewegungs- und Präsenzmelder
  {
    id: "loxone-presence-sensor-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Präsenzmelder Tree",
    description: "Präsenz, Bewegung, Helligkeit und akustische Präsenzerkennung.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "presence",
    color: TREE,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-presence-sensor-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Präsenzmelder Air",
    description: "Funkvariante des Präsenzmelders.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "presence",
    color: AIR,
    mountingType: "Decke",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-presence-sensor-ceiling-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Präsenzmelder Deckeneinbau Tree",
    description: "Deckenbündiger Präsenzmelder für feine Bewegungserkennung im Raum.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "presence",
    color: TREE,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-motion-sensor-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Bewegungsmelder Tree",
    description: "Bewegungsmelder für einfache Präsenzerkennung.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "motion",
    color: TREE,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-motion-sensor-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Bewegungsmelder Air",
    description: "Funkvariante des Bewegungsmelders.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "motion",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 4. Raumklima / Sensorik
  {
    id: "loxone-room-comfort-sensor-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Raumklima Sensor Tree",
    description: "Misst Temperatur, Luftfeuchtigkeit und Luftqualität im Raum.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "climate-sensor",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-room-comfort-sensor-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Raumklima Sensor Air",
    description: "Funkversion des Raumklima-Sensors.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "climate-sensor",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-temp-humidity-sensor-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Temperatur- und Feuchtesensor Air",
    description: "Misst Temperatur und Luftfeuchtigkeit.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "climate-sensor",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-smoke-presence-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "sicherheit-zutritt",
    label: "Rauch- & Präsenzmelder Tree",
    description: "Kombination aus Rauchmelder und Präsenzsensor.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "smoke",
    color: SECURITY,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-smoke-presence-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "sicherheit-zutritt",
    label: "Rauch- & Präsenzmelder Air",
    description: "Funkversion des kombinierten Rauch-/Präsenzmelders.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "smoke",
    color: SECURITY,
    mountingType: "Decke",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-smoke-detector-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "sicherheit-zutritt",
    label: "Rauchmelder Air",
    description: "Separater Rauchmelder ohne Präsenzfunktion.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "smoke",
    color: SECURITY,
    mountingType: "Decke",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 5. Fenster und Türen
  {
    id: "loxone-window-handle-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Fenstergriff Air",
    description: "Erkennt die Stellung des Fenstergriffs (geschlossen/geöffnet/gekippt).",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "window-contact",
    color: CONTACT,
    mountingType: "Fenster/Tür",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-window-contact",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Fensterkontakt",
    description: "Tür-/Fensterkontakt, z. B. als potentialfreier Kontakt über einen Tree- oder Nano-DI-Eingang realisiert.",
    technology: "loxone-tree",
    connectionType: "potentialfrei",
    icon: "window-contact",
    color: CONTACT,
    mountingType: "Fenster/Tür",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-window-contact-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Fensterkontakt Air",
    description: "Funk-Öffnungsmelder für Fenster, verbunden über Air Base Extension.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "window-contact",
    color: CONTACT,
    mountingType: "Fenster/Tür",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-door-contact",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Türkontakt",
    description: "Tür-/Fensterkontakt für Türen, z. B. als potentialfreier Kontakt realisiert.",
    technology: "loxone-tree",
    connectionType: "potentialfrei",
    icon: "door-contact",
    color: CONTACT,
    mountingType: "Fenster/Tür",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-door-contact-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Türkontakt Air",
    description: "Funk-Öffnungsmelder für Türen, verbunden über Air Base Extension.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "door-contact",
    color: CONTACT,
    mountingType: "Fenster/Tür",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 6. Zutritt / Eingangstür
  {
    id: "loxone-nfc-code-touch-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "sicherheit-zutritt",
    label: "NFC Code Touch Tree",
    description: "Zutrittskontrolle per NFC und Zahlencode.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "nfc",
    color: ACCESS,
    mountingType: "Außenwand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-nfc-code-touch-air",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "sicherheit-zutritt",
    label: "NFC Code Touch Air",
    description: "Air-Ausführung des NFC Code Touch.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "nfc",
    color: ACCESS,
    mountingType: "Außenwand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-door-lock-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "sicherheit-zutritt",
    label: "Door Lock Air",
    description: "Elektronisches Türschloss.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "door-lock",
    color: ACCESS,
    mountingType: "Fenster/Tür",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-intercom",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "sicherheit-zutritt",
    label: "Intercom",
    description: "Türkommunikation / Sprechanlage.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "intercom",
    color: ACCESS,
    mountingType: "Außenwand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 7. Beleuchtung – Loxone
  {
    id: "loxone-led-spot-ww-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Spot WW Tree",
    description: "Warmweiß-Deckenspot mit eigenem Tree-Anschluss.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "spot",
    color: LIGHT,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-led-spot-rgbw-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Spot RGBW Tree",
    description: "Deckenspot mit RGBW-Leuchtmittel und eigenem Tree-Anschluss.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "spot",
    color: RGBW,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-led-ceiling-rgbw-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Ceiling Light RGBW Tree",
    description: "RGBW-Deckenleuchte mit Tree-Anschluss.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "ceiling-light",
    color: RGBW,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-led-ceiling-rgbw-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Ceiling Light RGBW Air",
    description: "Air-Version der RGBW-Deckenleuchte.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "ceiling-light",
    color: RGBW,
    mountingType: "Decke",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-led-surface-spot-ww-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Deckenaufbauspot WW Tree",
    description: "Aufbauleuchte, warmweiß.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "spot",
    color: LIGHT,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-led-surface-spot-rgbw-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Aufbauspot RGBW Tree",
    description: "RGBW-Aufbauspot.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "spot",
    color: RGBW,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-led-pendant-rgbw-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Pendulum Slim RGBW Tree",
    description: "Pendelleuchte, z. B. für Esstisch, Kücheninsel oder Theke.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "ceiling-light",
    color: RGBW,
    mountingType: "Decke",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 8. LED-Bänder
  {
    id: "loxone-rgbw-led-strip",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "RGBW LED Strip / LED-Band",
    description:
      "Für Küche, Bad, Nische, indirekte Beleuchtung, Treppen, Möbel oder Decken. Wird als Linie mit Start- und Endpunkt geplant (siehe Hinweis unten).",
    technology: "loxone-tree",
    connectionType: "24V DC",
    icon: "led-strip",
    color: RGBW,
    mountingType: "Decke",
    cableType: "24V-Leitung",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-rgbw-dimmer-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "RGBW 24V Dimmer Tree",
    description: "Steuert 24-V-RGBW-Beleuchtung.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "dimmer",
    color: RGBW,
    mountingType: "Technikraum",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-rgbw-dimmer-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "RGBW 24V Dimmer Air",
    description: "Air-Ausführung des RGBW-Dimmers.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "dimmer",
    color: RGBW,
    mountingType: "Technikraum",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-led-spot-ww-pwm",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "LED Spot WW PWM",
    description: "PWM-gesteuerter Warmweiß-Spot.",
    technology: "loxone-tree",
    connectionType: "24V DC",
    icon: "spot",
    color: LIGHT,
    mountingType: "Decke",
    cableType: "24V-Leitung",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 9. Beschattung
  {
    id: "loxone-shading-actuator-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beschattung",
    label: "Beschattungs Aktor Air",
    description: "Steuerung von Rollläden, Jalousien oder Markisen.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "shading",
    color: SHADING,
    mountingType: "Technikraum",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-nano-motor-controller-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beschattung",
    label: "Nano Motor Controller Tree",
    description: "Steuert einen Beschattungsmotor, dezentral verbaut.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "shading",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-nano-motor-controller-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beschattung",
    label: "Nano Motor Controller Air",
    description: "Air-Ausführung des Nano Motor Controllers.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "shading",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-jalousie-antrieb-gj56-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beschattung",
    label: "Jalousieantrieb GJ56 Air",
    description: "Direkter Air-Jalousieantrieb.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "shading",
    color: SHADING,
    mountingType: "Decke",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-geiger-solidline-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beschattung",
    label: "GEIGER SOLIDline Air",
    description: "Rollladen-/Sonnenschutzmotor mit Loxone Air.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "shading",
    color: SHADING,
    mountingType: "Decke",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 10. Heizung
  {
    id: "loxone-valve-actuator-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "climate",
    planningCategory: "heizung-klima",
    label: "Stellantrieb Tree",
    description: "Steuert Heizkörper- oder Fußbodenheizungsventile, normalerweise am Heizkreisverteiler.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "valve",
    color: HEATING,
    mountingType: "Technikraum",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-valve-actuator-air",
    systemId: LOXONE_SYSTEM.id,
    category: "climate",
    planningCategory: "heizung-klima",
    label: "Stellantrieb Air",
    description: "Air-Ausführung des Heizungsstellantriebs.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "valve",
    color: HEATING,
    mountingType: "Technikraum",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 11. Klima / Klimaanlagen
  ...(
    [
      ["lg", "LG"],
      ["panasonic", "Panasonic"],
      ["daikin-p1p2", "Daikin P1P2"],
      ["daikin-s21", "Daikin S21"],
      ["fujitsu", "Fujitsu"],
      ["gree-sinclair", "Gree / Sinclair"],
      ["mitsubishi-electric", "Mitsubishi Electric"],
      ["mitsubishi-heavy", "Mitsubishi Heavy Industries"],
      ["toshiba", "Toshiba"],
    ] as const
  ).map(([slug, brand]) => ({
    id: `loxone-ac-control-air-${slug}`,
    systemId: LOXONE_SYSTEM.id,
    category: "climate" as const,
    planningCategory: "heizung-klima" as const,
    label: `AC Control Air für ${brand}`,
    description: `Loxone-Anbindung für Klimaanlagen von ${brand}.`,
    technology: "loxone-air" as const,
    connectionType: "Air" as const,
    icon: "ac" as const,
    color: HEATING,
    mountingType: "Technikraum" as const,
    powerSupply: "230V AC" as const,
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  })),

  // 12. Lüftung
  {
    id: "loxone-leaf-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "climate",
    planningCategory: "heizung-klima",
    label: "Leaf Tree",
    description: "Loxone-Lüftungskomponente.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "ventilation",
    color: HEATING,
    mountingType: "Technikraum",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-leaf-air",
    systemId: LOXONE_SYSTEM.id,
    category: "climate",
    planningCategory: "heizung-klima",
    label: "Leaf Air",
    description: "Air-Ausführung der Lüftungskomponente.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "ventilation",
    color: HEATING,
    mountingType: "Technikraum",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 13. Sicherheit
  {
    id: "loxone-alarm-siren-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "sicherheit-zutritt",
    label: "Alarmsirene Tree",
    description: "Sirene für innen oder außen, je nach Einsatz.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "siren",
    color: SECURITY,
    mountingType: "Außenwand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-alarm-siren-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "sicherheit-zutritt",
    label: "Alarmsirene Air",
    description: "Funkvariante der Alarmsirene.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "siren",
    color: SECURITY,
    mountingType: "Außenwand",
    powerSupply: "Batterie",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 14. Audio Zentrale
  {
    id: "loxone-audioserver",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "audio",
    label: "Audioserver",
    description: "Zentrale Audiokomponente, normalerweise im Technikraum nahe dem Schaltschrank.",
    technology: "audio",
    connectionType: "Ethernet",
    icon: "audio-server",
    color: AUDIO,
    mountingType: "Technikraum",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-stereo-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "audio",
    label: "Stereo Extension",
    description: "Erweitert das Audiosystem um weitere Lautsprecherkanäle.",
    technology: "audio",
    connectionType: "Ethernet",
    icon: "audio-server",
    color: AUDIO,
    mountingType: "Schaltschrank/Hutschiene",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },

  // 15. Loxone Lautsprecher
  {
    id: "loxone-install-speaker-7-master",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Install Speaker 7 Master",
    description: "Deckeneinbau-Lautsprecher, Master eines Kanalpaars.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Decke",
    cableType: "Lautsprecherkabel 2x1,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-install-speaker-7-client",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Install Speaker 7 Client",
    description: "Client-Lautsprecher zum Install Speaker 7 Master.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Decke",
    cableType: "Lautsprecherkabel 2x1,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-install-speaker-10-master",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Install Speaker 10 Master",
    description: "Größerer Deckeneinbau-Lautsprecher, Master.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Decke",
    cableType: "Lautsprecherkabel 2x2,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-install-speaker-10-client",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Install Speaker 10 Client",
    description: "Client-Lautsprecher zum Install Speaker 10 Master.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Decke",
    cableType: "Lautsprecherkabel 2x2,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-install-sub-10-master",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Install Sub 10 Master",
    description: "Einbau-Subwoofer, Master.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Decke",
    cableType: "Lautsprecherkabel 2x2,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-install-sub-10-client",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Install Sub 10 Client",
    description: "Client-Subwoofer zum Install Sub 10 Master.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Decke",
    cableType: "Lautsprecherkabel 2x2,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-satellite-speaker-ip64-master",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Satellite Speaker IP64 Master",
    description: "Spritzwassergeschützter Lautsprecher, geeignet für Außenbereich, Terrasse oder Feuchträume.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Außenwand",
    cableType: "Lautsprecherkabel 2x1,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-satellite-speaker-ip64-client",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Satellite Speaker IP64 Client",
    description: "Client-Lautsprecher zum Satellite Speaker IP64 Master.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Außenwand",
    cableType: "Lautsprecherkabel 2x1,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-satellite-speaker-ip64-passive",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Satellite Speaker IP64 Passive",
    description: "Passiver Satellite Speaker.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Außenwand",
    cableType: "Lautsprecherkabel 2x1,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-wireless-speaker",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Wireless Speaker",
    description: "Kabelloser Loxone-Lautsprecher.",
    technology: "audio",
    connectionType: "WiFi",
    icon: "speaker",
    color: AUDIO,
    mountingType: "frei",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-wall-speaker",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "audio",
    label: "Wall Speaker",
    description: "Wandlautsprecher.",
    technology: "audio",
    connectionType: "230V",
    icon: "speaker",
    color: AUDIO,
    mountingType: "Wand",
    cableType: "Lautsprecherkabel 2x1,5",
    powerSupply: "keine",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 17. Steckdosen
  {
    id: "loxone-smart-socket-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "steckdosen-strom",
    label: "Smart Socket Air",
    description: "Loxone-Funksteckdose.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "outlet",
    color: OUTLET,
    mountingType: "frei",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 19. Netzwerk
  {
    id: "loxone-wlan-access-point",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "netzwerk",
    label: "WLAN Access Point",
    description: "WLAN-Zugangspunkt, an Decke oder Wand montiert.",
    technology: "network",
    connectionType: "Ethernet",
    icon: "network",
    color: NETWORK,
    mountingType: "Decke",
    cableType: "CAT7",
    powerSupply: "PoE",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 20-21. Tree- / Air-Infrastruktur, 22. Schaltschrank Extensions
  {
    id: "loxone-tree-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Tree Extension",
    description: "Erweitert den Miniserver um Tree-Kommunikation.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-air-base-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Air Base Extension",
    description: "Erweitert ein System um Loxone Air — Air-Geräte benötigen keine Tree-Datenleitung.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-relay-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "schaltschrank-technik",
    label: "Relay Extension",
    description: "14 potentialfreie Relaisausgänge.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "relay",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-dimmer-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "schaltschrank-technik",
    label: "Dimmer Extension",
    description: "Zum Dimmen klassischer Leuchtmittel.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "dimmer",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-di-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "schaltschrank-technik",
    label: "DI Extension",
    description: "Digitale Eingänge.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "io-module",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-ai-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "schaltschrank-technik",
    label: "AI Extension",
    description: "Analoge Eingänge.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "io-module",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-ao-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "schaltschrank-technik",
    label: "AO Extension",
    description: "Analoge Ausgänge.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "io-module",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-multi-extension-air",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Multi Extension Air",
    description: "Mehrere Ein-/Ausgänge über Air.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-dali-extension-64",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "schnittstellen-extensions",
    label: "DALI Extension – 64 Geräte",
    description: "DALI-Beleuchtung, bis zu 64 Geräte.",
    technology: "loxone-tree",
    connectionType: "DALI",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-dali-extension-10",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "schnittstellen-extensions",
    label: "DALI Extension – 10 Geräte",
    description: "Kleinere DALI-Lösung, bis zu 10 Geräte.",
    technology: "loxone-tree",
    connectionType: "DALI",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-dmx-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "schnittstellen-extensions",
    label: "DMX Extension",
    description: "DMX-Anbindung.",
    technology: "loxone-tree",
    connectionType: "DMX",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-modbus-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "Modbus Extension",
    description: "Modbus-Kommunikation.",
    technology: "loxone-tree",
    connectionType: "Modbus",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-rs232-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "RS232 Extension",
    description: "Serielle Schnittstelle.",
    technology: "loxone-tree",
    connectionType: "RS232",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-rs485-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "RS485 Extension",
    description: "Serielle Schnittstelle.",
    technology: "loxone-tree",
    connectionType: "RS485",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-knx-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "KNX Extension",
    description: "KNX-Anbindung.",
    technology: "loxone-tree",
    connectionType: "KNX",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-enocean-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "EnOcean Extension",
    description: "EnOcean-Geräte.",
    technology: "loxone-tree",
    connectionType: "EnOcean",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-1wire-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "1-Wire Extension",
    description: "1-Wire-Sensoren.",
    technology: "loxone-tree",
    connectionType: "1-Wire",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-mbus-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "M-Bus Extension",
    description: "M-Bus-Anbindung.",
    technology: "loxone-tree",
    connectionType: "M-Bus",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-ir-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "IR Extension",
    description: "Infrarot-Anbindung.",
    technology: "loxone-tree",
    connectionType: "IR",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-internorm-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "Internorm Extension",
    description: "Internorm-Systemintegration.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-froeling-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "Fröling Extension",
    description: "Integration von Fröling-Heizungsanlagen.",
    technology: "loxone-tree",
    connectionType: "Modbus",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-schueco-extension",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schnittstellen-extensions",
    label: "Schüco Extension",
    description: "Integration von Schüco-Systemen.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "extension",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },

  // 23. Kleine Einbaumodule (dezentral, am/im Gerät verbaut)
  {
    id: "loxone-nano-2-relay-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "geraete-raum",
    label: "Nano 2 Relay Tree",
    description: "Kleine dezentrale Relaislösung, direkt am Verbraucher verbaut.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "relay",
    color: TREE,
    mountingType: "frei",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-nano-di-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "input",
    planningCategory: "geraete-raum",
    label: "Nano DI Tree",
    description: "Digitale Eingänge, dezentral verbaut — geeignet für Fensterkontakte, Türkontakte, Taster und Sensoren.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "io-module",
    color: TREE,
    mountingType: "frei",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-nano-dimmer-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "Nano Dimmer Tree",
    description: "Unterputz-Dimmer für eine einzelne Leuchte.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "dimmer",
    color: TREE,
    mountingType: "Wand",
    cableType: "Tree Cable",
    powerSupply: "Tree-Bus",
    countsAsTreeDevice: true,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-nano-dimmer-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "beleuchtung",
    label: "Nano Dimmer Air",
    description: "Air-Ausführung des Unterputz-Dimmers.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "dimmer",
    color: AIR,
    mountingType: "Wand",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-nano-io-air",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "geraete-raum",
    label: "Nano IO Air",
    description: "Ein-/Ausgangsmodul, dezentral verbaut.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "io-module",
    color: AIR,
    mountingType: "frei",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },
  {
    id: "loxone-nano-relay-air",
    systemId: LOXONE_SYSTEM.id,
    category: "actuator",
    planningCategory: "geraete-raum",
    label: "Nano Relay Air",
    description: "Funkrelais, dezentral verbaut.",
    technology: "loxone-air",
    connectionType: "Air",
    icon: "relay",
    color: AIR,
    mountingType: "frei",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: true,
    isCabinetComponent: false,
  },

  // 24. Energie
  {
    id: "loxone-energy-meter-1phase-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "schaltschrank-technik",
    label: "Energiezähler 1-phasig Tree",
    description: "Einphasiger Energiezähler für den Schaltschrank.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "energy-meter",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-energy-meter-3phase-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "schaltschrank-technik",
    label: "Energiezähler 3-phasig Tree",
    description: "Dreiphasiger Energiezähler für den Schaltschrank.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "energy-meter",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-energy-meter-ct-1-5a-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "schaltschrank-technik",
    label: "Energiezähler für 1A/5A Stromwandler Tree",
    description: "Energiezähler für 1A- bzw. 5A-Stromwandler.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "energy-meter",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-energy-meter-ct-40ma-tree",
    systemId: LOXONE_SYSTEM.id,
    category: "sensor",
    planningCategory: "schaltschrank-technik",
    label: "Energiezähler für 40-mA-Stromwandler Tree",
    description: "Energiezähler für 40-mA-Stromwandler.",
    technology: "loxone-tree",
    connectionType: "Tree",
    icon: "energy-meter",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    cableType: "Tree Cable",
    powerSupply: "24V DC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },

  // 25. Stromversorgung
  {
    id: "loxone-power-supply",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Loxone Power Supply",
    description: "24-V-Spannungsversorgung für die Tree-Geräte.",
    technology: "loxone-tree",
    connectionType: "24V DC",
    icon: "power-supply",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
  {
    id: "loxone-power-supply-backup",
    systemId: LOXONE_SYSTEM.id,
    category: "controller",
    planningCategory: "schaltschrank-technik",
    label: "Power Supply & Backup",
    description: "24-V-Versorgung mit Backup-Funktion.",
    technology: "loxone-tree",
    connectionType: "24V DC",
    icon: "power-supply",
    color: CABINET,
    mountingType: "Schaltschrank/Hutschiene",
    powerSupply: "230V AC",
    countsAsTreeDevice: false,
    isPlanableOnFloorplan: false,
    isCabinetComponent: true,
  },
];

const SMART_HOME_CATALOGS: Record<string, SmartHomeDeviceModel[]> = {
  [LOXONE_SYSTEM.id]: LOXONE_CATALOG,
};

export function getSmartHomeCatalog(systemId: string): SmartHomeDeviceModel[] {
  return SMART_HOME_CATALOGS[systemId] ?? [];
}

export function findSmartHomeModel(modelId: string): SmartHomeDeviceModel | undefined {
  return Object.values(SMART_HOME_CATALOGS)
    .flat()
    .find((model) => model.id === modelId);
}

/** Which hardware categories are plausible for each placeable electrical
 * device type — narrows the picker instead of showing the full catalog
 * everywhere. Network sockets have no Loxone hardware role, so they're
 * simply omitted rather than mapped to something misleading. */
export const DEVICE_TYPE_SMART_HOME_CATEGORIES: Partial<
  Record<ElectricalDeviceType, SmartHomeDeviceCategory[]>
> = {
  outlet: ["actuator"],
  light: ["actuator"],
  switch: ["input"],
  sensor: ["sensor", "climate"],
};

export const DISTRIBUTION_BOARD_SMART_HOME_CATEGORIES: SmartHomeDeviceCategory[] = [
  "controller",
];

/** Every category — used by the standalone Smart-Home placement tool,
 * where the user picks freely from the whole catalog. */
export const ALL_SMART_HOME_CATEGORIES: SmartHomeDeviceCategory[] = [
  "controller",
  "actuator",
  "input",
  "sensor",
  "climate",
];
